---
# tasks file for sprylab.tomcat-ubuntu

- name: Create download directory for Tomcat packages
  file:
     path: "{{ tomcat_ubuntu_download_dir }}"
     state: directory
     mode: 0755

- name: Download Tomcat from Ubuntu Package archive
  get_url:
    url: "{{ item }}"
    dest: "{{ tomcat_ubuntu_download_dir }}"
  with_items:
    - "{{ tomcat_ubuntu_repository }}/pool/main/t/tomcat8/tomcat8_{{ tomcat_ubuntu_version }}.deb"
    - "{{ tomcat_ubuntu_repository }}/pool/main/t/tomcat8/tomcat8-common_{{ tomcat_ubuntu_version }}.deb"
    - "{{ tomcat_ubuntu_repository }}/pool/main/t/tomcat8/libtomcat8-java_{{ tomcat_ubuntu_version }}.deb"
    - "{{ tomcat_ubuntu_repository }}/pool/main/e/ecj/libecj-java_{{ tomcat_ubuntu_libecj_version }}.deb"
    - "{{ tomcat_ubuntu_repository }}/pool/main/o/openssl/libssl1.0.0_{{ tomcat_ubuntu_libssl_version }}.deb"

- name: Download Tomcat Admin from Ubuntu Package archive
  get_url:
    url: "{{ tomcat_ubuntu_repository }}/pool/main/t/tomcat8/tomcat8-admin_{{ tomcat_ubuntu_version }}.deb"
    dest: "{{ tomcat_ubuntu_download_dir }}"
  when: tomcat_ubuntu_admin_install|bool

- name: Download Tomcat User from Ubuntu Package archive
  get_url:
    url: "{{ tomcat_ubuntu_repository }}/pool/universe/t/tomcat8/tomcat8-user_{{ tomcat_ubuntu_version }}.deb"
    dest: "{{ tomcat_ubuntu_download_dir }}"
  when: tomcat_ubuntu_user_install|bool

- name: Download Tomcat Native Library from Ubuntu Package archive
  get_url:
    url: "{{ item }}"
    dest: "{{ tomcat_ubuntu_download_dir }}"
  with_items:
    - "{{ tomcat_ubuntu_repository }}/pool/universe/t/tomcat-native/libtcnative-1_{{ tomcat_ubuntu_native_version }}.deb"
    - "{{ tomcat_ubuntu_repository }}/pool/main/a/apr/libapr1_{{ tomcat_ubuntu_apache_native_version }}.deb"
  when: tomcat_ubuntu_native_install|bool

- name: Install Tomcat packages
  sudo: yes
  apt:
    deb: "{{ tomcat_ubuntu_download_dir }}/{{ item.1 }}"
  with_indexed_items:
    - libssl1.0.0_{{ tomcat_ubuntu_libssl_version }}.deb
    - libecj-java_{{ tomcat_ubuntu_libecj_version }}.deb
    - libtomcat8-java_{{ tomcat_ubuntu_version }}.deb
    - tomcat8-common_{{ tomcat_ubuntu_version }}.deb
    - tomcat8_{{ tomcat_ubuntu_version }}.deb

- name: Install Tomcat Admin package
  sudo: yes
  apt:
    deb: "{{ tomcat_ubuntu_download_dir }}/tomcat8-admin_{{ tomcat_ubuntu_version }}.deb"
  when: tomcat_ubuntu_admin_install|bool

- name: Install Tomcat User package
  sudo: yes
  apt:
    deb: "{{ tomcat_ubuntu_download_dir }}/tomcat8-user_{{ tomcat_ubuntu_version }}.deb"
  when: tomcat_ubuntu_user_install|bool

- name: Install Tomcat Native Library packages
  sudo: yes
  apt:
    deb: "{{ tomcat_ubuntu_download_dir }}/{{ item.1 }}"
  with_indexed_items:
    - libapr1_{{ tomcat_ubuntu_apache_native_version }}.deb
    - libtcnative-1_{{ tomcat_ubuntu_native_version }}.deb
  when: tomcat_ubuntu_native_install|bool

# see https://bugs.launchpad.net/ubuntu/+source/tomcat-native/+bug/1326255 for details
- name: Fix Tomcat Native Library Ubuntu packaging bug
  sudo: yes
  file:
    path: /usr/lib/libtcnative-1.so
    src: /usr/lib/x86_64-linux-gnu/libtcnative-1.so
    state: link
  when: tomcat_ubuntu_native_install|bool

- name: Enable Tomcat system user to re-deploy to root context (/)
  sudo: yes
  file:
    path: /var/lib/tomcat8/webapps/ROOT
    state: directory
    owner: tomcat8
    group: tomcat8

- name: Update Tomcat's server.xml
  sudo: yes
  template:
    src: ../templates/server.j2
    dest: /var/lib/tomcat8/conf/server.xml
  notify:
    - restart tomcat

- name: Update Tomcat's tomcat-users.xml
  sudo: yes
  template:
    src: ../templates/tomcat-users.j2
    dest: /var/lib/tomcat8/conf/tomcat-users.xml
  notify:
    - restart tomcat

- name: Set Tomcat's JAVA_OPTS
  sudo: yes
  lineinfile:
    dest: /etc/default/tomcat8
    state: present
    regexp: '^JAVA_OPTS=.*$'
    line: 'JAVA_OPTS="{{ tomcat_ubuntu_java_opts }}"'
  notify:
    - restart tomcat
  tags:
    - jvm-options

- name: Set Tomcat's CATALINA_OPTS
  sudo: yes
  lineinfile:
    dest: /etc/default/tomcat8
    state: present
    regexp: '^CATALINA_OPTS=.*$'
    line: 'CATALINA_OPTS="{{ tomcat_ubuntu_catalina_opts }}"'
    insertafter: '^JAVA_OPTS=.*$'
  notify:
    - restart tomcat
  when: tomcat_ubuntu_catalina_opts is defined
  tags:
    - jvm-options

- name: Download MySQL JBDC Driver
  sudo: yes
  apt:
    name: libmysql-java
  when: tomcat_ubuntu_mysql_jbdc_install

- name: Enable MySQL JBDC Driver
  sudo: yes
  file:
      path: /usr/share/tomcat8/lib/mysql-connector-java.jar
      src: /usr/share/java/mysql-connector-java.jar
      state: link
  when: tomcat_ubuntu_mysql_jbdc_install
  notify:
    - restart tomcat

- name: Download PostgreSQL JBDC Driver
  sudo: yes
  get_url:
    url: http://search.maven.org/remotecontent?filepath=org/postgresql/postgresql/{{ tomcat_ubuntu_postgresql_jdbc_version }}/postgresql-{{ tomcat_ubuntu_postgresql_jdbc_version }}.jar
    dest: /usr/share/tomcat8/lib/
  when: tomcat_ubuntu_postgresql_jbdc_install
  notify:
    - restart tomcat

- name: Create additional Tomcat user instance(s)
  include: user-instance.yml
  vars:
    - user_instance: "{{ item }}"
  with_items: "{{ tomcat_ubuntu_user_instances }}"
  when: tomcat_ubuntu_user_install|bool and tomcat_ubuntu_user_instances is defined
  tags:
    - user-instances